---
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: ensure dnsmasq and darkhttpd are installed
      pacman:
        name:
          - dnsmasq
          - darkhttpd
        state: present
